# Data params
input_dir: /data2/steggema/snd/pt/
artifacts: /home/steggema/snd/artifacts/
project: SNDRecoExphormer
model: Exphormer
nodes: 1

# Dataset parameters
data_split: [144000, 50400, 50400] # [1440000, 504000, 504000]
feature_set: [vertical, strip_x, strip_y, strip_z, strip_x_end, strip_y_end, strip_z_end, det]
nb_classes: 5

# Training params
max_epochs: 10
lr: 0.003
factor: 0.93
patience: 2
warmup: 10
scheduler: StepLR
train_batch: 250
val_batch: 250
final_dropout: 0.1 # The dropout of the final layer
feature_dropout: 0.0 # This is the dropout within the GNN convolutions
spatial_dropout: 0.0
class_weights: [2., 1.5, 1., 0.3, 1.]

# graph_construction: fully_connected # this crashes badly

model_graph_pooling: max

prep_exp: True
prep_exp_deg: 3  # Algorithm will use 3 permutations or 3 Hamiltonian cycles, so actual degree will be 6
prep_add_edge_index: True # Set True if you want to add real edges beside expander edges
prep_num_virt_node: 0 # Set True if you want to add global node connections beside expander edges
prep_use_exp_edges: False

dataset_node_encoder: True
dataset_node_encoder_name: LinearNode
dataset_node_encoder_bn: False
dataset_edge_encoder: True
dataset_edge_encoder_name: DummyEdge
dataset_edge_encoder_bn: False

gt_layer_type: CustomGatedGCN+Exphormer
gt_layers: 4
gt_n_heads: 8
gt_dim_hidden: 96  # `gt.dim_hidden` must match `gnn.dim_inner`
gt_dropout: 0.15
gt_attn_dropout: 0.5
gt_layer_norm: False
gt_batch_norm: True

gnn_head: mygraph
gnn_layers_pre_mp: 0
gnn_layers_post_mp: 3
gnn_dim_inner: 96  # `gt.dim_hidden` must match `gnn.dim_inner`
gnn_batchnorm: True
gnn_act: relu
gnn_dropout: 0.0
gnn_agg: mean
gnn_normalize_adj: False