# Data params
input_dir: /data2/steggema/snd/pt/
artifacts: /home/steggema/snd/artifacts/
project: GeometricAttention
model: GravNet
nodes: 1

# Dataset parameters
data_split: [10000, 10000, 10000]
feature_set: [vertical, strip_x, strip_y, strip_z, strip_x_end, strip_y_end, strip_z_end, det]
nb_classes: 7

# Training params
max_epochs: 20
lr: 0.003
factor: 0.9
patience: 2
warmup: 10
scheduler: StepLR
train_batch: 800
val_batch: 800
final_dropout: 0.2 # The dropout of the final layer
feature_dropout: 0. # This is the dropout within the GNN convolutions
spatial_dropout: 0.
signal_goal: 0.8 # The efficiency goal for the signal neutrinos
pos_weight:

# MLP params
edge_cut: 0.5
spatial_channels:
layernorm: True
batchnorm: True
aggregation: mean_sum
hidden_activation: SiLU
output_activation: 

# Layer Structure
hidden: 64
n_graph_iters: 2
nb_node_layer: 2
nb_edge_layer: 2
concat_all_layers: True
layer_shape: flat

# GravNet-specific parameters
knn: 
rand_k: 

r: 0.1
max_knn: 8

emb_dims: 16
grav_weight: 3.0
norm_hidden: True
norm_embedding: True
self_loop: False
