# Data params
input_dir: /data2/steggema/toptagtest/
artifacts: /data2/steggema/toptagtest/artifacts/
project: GeometricAttention
model: GravNetExt # GravNet
nodes: 1

# Dataset parameters
data_split: [1200000,400000,400000]
feature_set: [pE, py, px, pz, delta_eta, log_delta_E, delta_phi, log_pt, log_E, log_delta_pt, delta_pt, delta_E, delta_R,
              jet_pt, jet_mass, jet_phi, jet_eta, jet_pE, jet_px, jet_py, jet_pz]
nb_classes: 1

# Training params
max_epochs: 10
lr: 0.003 # 0.005
factor: 0.9
patience: 2
warmup: 10
scheduler: StepLR
train_batch: 400 # 800
val_batch: 400 # 800
final_dropout: 0.2 # The dropout of the final layer
feature_dropout: 0. # This is the dropout within the GNN convolutions
spatial_dropout: 0.
signal_goal: 0.3 # The efficiency goal for the signal jets
pos_weight: 1.

# MLP params
edge_cut: 0.5
spatial_channels:
layernorm: False # True
batchnorm: True
aggregation: mean_sum
hidden_activation: SiLU # ReLU 
output_activation: 

# Layer Structure
n_grav_heads: 8 # 2
hidden: 256
n_graph_iters: 3
nb_encoder_layer: 3
nb_decoder_layer: 3
nb_feature_layer: 3
nb_spatial_layer: 3
n_conv_layer: 2
concat_all_layers: False # True
layer_shape: pyramid # flat

# GravNet-specific parameters
knn: 
rand_k: 
aggs: [add, max] # [add, max, mean] # [add] 
r: 0.1
max_knn: 16
use_attention_weight: True

emb_dims: 64
grav_weight: 3.0
norm_hidden: True
norm_embedding: True
self_loop: False
